[package]
name = "what-note"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
clap = {version = "3.0.7", features = ["derive", "wrap_help"]}
rand = "0.8"
regex = "1.5"
once_cell = "1.8"
